apiVersion: v1
kind: Service
metadata:
  labels:
    app: vbless-ui
  name: vbless-ui
spec:
  selector:
    app: vbless-ui
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer  
